#!/bin/sh

NAMESPACE=$KUBECTL_PLUGINS_CURRENT_NAMESPACE

# ensure docker executable exists
ensureDockerExists() {
    if [ -z "$(which docker)" ]; then
        echo "docker executable not found ... is it installed?"
        exit 1
    fi
}

# get kubernetes secret
getSecret() {
  kubectl get secrets $1 -o json -n $NAMESPACE
}

# decode kubernetes secret
decodeSecret() {
    docker run -i normanjoyner/jq:1.6_rc1-r1 '.data | to_entries | map(. + {"value": .value | @base64d }) | from_entries'
}

ensureDockerExists
getSecret $1 | decodeSecret
